name: Test automation

on:
  push:
    branches:
    - "main"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup scala environment
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "openjdk@1.17"
      - name: Run plugin tests
        run: sbt -v -Dfile.encoding=UTF-8 +scripted