name: Build and test

on:
  push:
    branches-ignore:
    - main
    paths-ignore:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - renovate.json
      - '.github/workflows/**'
      - .releaserc.yaml
      - 'package*.json'
  workflow_call:

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        java:
          - openjdk@1.17
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup scala environment
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Lint with scalafmt
        run: sbt scalafmtCheckAll
      - name: Check with scalafix
        run: sbt 'scalafixAll --check'
      - name: Test plugins
        run: sbt scripted